apiVersion: v1
kind: Service
metadata:
  name: to-do-app-service
  namespace: Your Namespace Name
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: to-do-app
  ports:
    - protocol: TCP
      port: 8050
      targetPort: 5000

